export interface IPacketEntityHttp {
    http_http_cache_control: string;
    http_http_connection: string;
    http_http_content_length_header: string;
    http_http_content_type: string;
    http_http_date: string;
    http_http_file_data: string;
    http_http_host: string;
    http_http_request: string;
    http_http_request_in: string;
    http_http_request_full_uri: string;
    http_http_request_line: string[];
    http_http_request_number: string;
    http_http_user_agent: string;
    http_http_response: string;
    http_http_response_for_uri: string;
    http_http_response_line: string[];
    http_http_response_number: string;
    http_http_server: string;
    http_http_time: string;
    http_text: string;
    text_http_request_method: string;
    text_http_request_uri: string;
    text_http_request_version: string;
    text_http_response_code: string;
    text_http_response_code_desc: string;
    text_http_response_phrase: string;
    text_http_response_version: string;
}
