version: '3.2'

services:
  analyst:
    build:
      context: ../analyst-app
    restart: on-failure
    network_mode: host

  db:
    image: postgres
    restart: always
    volumes:
      - type: volume
        source: postgres
        target: $POSTGRES_CONTAINER_DATA
      - type: bind
        source: ./db/init.sql
        target: /docker-entrypoint-initdb.d/10-init.sql
        read_only: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

volumes:
  postgres:
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
