version: '3.2'

services:
  tshark:
    build:
      context: tshark
      args:
        ELASTIC_HOST: $ELASTIC_HOST
        ELASTIC_USERNAME: $ELASTIC_USERNAME
        ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    restart: on-failure
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
